### ISSUE TITLE
Display day of the week

### ISSUE THREAD

**Issue by ZZZooHaq** [debater-coder/timetabl-app#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by debater-coder** [comment]
I haven't thought of a good place to put this information. If you have any ideas, you could make a mockup. For now, this information is planned to be implemented in the calendar.

**Comment by wensenfriendandextra** [comment]
maybe eg XXXday DD/MM/YYYY in the input?

**Comment by wensenfriendandextra** [comment]
![image](https://user-images.githubusercontent.com/23128324/208291222-947987c1-c002-47ff-af79-f43c6ea34fd6.png)

**Comment by debater-coder** [comment]
I guess that works. Would you like to open a PR 😜?

**Comment by debater-coder** [comment]
Actually, it has been very hard to get everything to fit, so maybe this should only be implemented after I figure out some auto-fitting algorithm. (Responsive UI is not that easy, and I don't want to go Paragon's route of making things so small that they are illegible.)

**Comment by wensenfriendandextra** [comment]
Not just you...
