### ISSUE TITLE
background colour customisation

### ISSUE THREAD

**Issue by ZZZooHaq** [debater-coder/timetabl-app#14]
**Is your feature request related to a problem? Please describe.**
I would like to set the background colour so that it complements the colour I chose so that I can create a variety of themes.

**Describe the solution you'd like**
I would like a colour picker where you can choose the colour.

**Describe alternatives you've considered**
There could be a bunch of pre-selected colours where you could choose from.

**Comment by debater-coder** [comment]
This will be implemented as part of #32 (Timetabl Themes).
