### ISSUE TITLE
Add unauthenticated access to bells

### ISSUE THREAD

**Issue by wensenfriendandextra** [debater-coder/timetabl-app#23]
Currently, you must sign in to see your classes. My feature request is to add unauthentiated access to bells because unauthenticated access is good

**Comment by debater-coder** [comment]
no

**Comment by debater-coder** [comment]
ok

**Comment by debater-coder** [comment]
I don't think this feature adds any value to the app, so unless you can explain the value it adds I am closing this issue. Thank you for your feedback.

**Comment by wensenfriendandextra** [comment]
ehh probably for parents who need to pick up their children and need to know when best to do it and also for changed school end times (e.g. ending at 2pm instead of 3:15pm cuz interviews and it changing to 3:10pm as well)

**Comment by wensenfriendandextra** [comment]
@debater-coder

**Comment by debater-coder** [comment]
That seems like a very niche use case and not something that fits the vision of Timetabl in general.
