### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by wensenfriendandextra** [debater-coder/timetabl-app#26]
filter to your year group => filter for your year group?
[/src/routes/Landing/Features.tsx](https://github.com/debater-coder/timetabl-app/blob/main/src/routes/Landing/Features.tsx)

**Comment by wensenfriendandextra** [comment]
Also in [src/routes/Landing/Features.tsx](https://github.com/debater-coder/timetabl-app/pull/25/commits/a0c759e2d54f7290ec3f35c6d02cff4fba93d5c6#diff-da0d7289657ef04564fbb232007219e074b56b1111427847fda89efeb981726c)

**Comment by wensenfriendandextra** [comment]
Also in [/src/routes/Landing/Features.tsx](https://github.com/debater-coder/timetabl-app/blob/main/src/routes/Landing/Features.tsx)

**Comment by debater-coder** [comment]
That is definitely a typo. Thanks for the catch!

**Comment by wensenfriendandextra** [comment]
#30 fixes this

**Comment by wensenfriendandextra** [comment]
Closing as #30 exists now, pls use that :)))))))))))))))))))))))
