### ISSUE TITLE
Typo in announcements

### ISSUE THREAD

**Issue by lol-idk-hehe** [debater-coder/timetabl-app#7]
**Describe the bug**
In the announcements tab, it says "annnouncements", not "announcments"

**To Reproduce**
1. Go to 'Announcements'
2. Be amazed a the title typo

**Expected behavior**
I expected announcements to be spelt properly lol.

**Screenshots**
![yes](https://pasteboard.co/LUwO5AYVzeto.png)
(link doesn't work, pastebin here https://pasteboard.co/LUwO5AYVzeto.png)
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome PWA
 - Chrome Version: 106.0.5249.103 (Official Build) (64-bit) (cohort: Rampup_106)

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS: n/a
 - Browser: n/a
 - Version: n/a

**Additional context**

**Comment by debater-coder** [comment]
Thanks for the catch!
