### ISSUE TITLE
Timetable does not show other dates through default date selector, and custom arrows do not work

### ISSUE THREAD

**Issue by wensenfriendandextra** [debater-coder/timetabl-app#71]
Timetable does not show other dates through default date selector, and custom arrows do not work

**Comment by wensenfriendandextra** [comment]
Default date selector
![image](https://user-images.githubusercontent.com/23128324/215737431-556cc709-c834-4fe6-882d-0dd3bf2320d4.png)

**Comment by wensenfriendandextra** [comment]
Arrows
![image](https://user-images.githubusercontent.com/23128324/215737496-b70ad0c2-caa5-4c0e-b46a-5dd4738254d3.png)

**Comment by debater-coder** [comment]
I'm currently on vacation but this will be my priority as soon as I get back.

**Comment by debater-coder** [comment]
This is now fixed
