### ISSUE TITLE
Handle Casual Teachers and Room Changes

### ISSUE THREAD

**Issue by debater-coder** [debater-coder/timetabl-app#8]
**Describe the bug**
Timetabl does not display casual teachers and room changes

**To Reproduce**
1. Navigate to a day where a casual teacher or room change has been indicated in the school API.
2. Observe how these changes are not displayed.

**Expected behavior**
Casual teachers and room changes should be displayed and highlighted.

**Additional context**
This is a relatively easy issue to solve, but I have not been able to get around to it. If you are interested in solving it yourself, please drop a comment down below and when you are ready, submit a PR.

**Comment by wensenfriendandextra** [comment]
bump

**Comment by debater-coder** [comment]
Timetabl now handles casual teachers.

**Comment by debater-coder** [comment]
But it didn't handle room changes... Until now!

Closing issue.
