### ISSUE TITLE
Stub-like MD files

### ISSUE THREAD

**Issue by wensenfriendandextra** [debater-coder/timetabl-app#86]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I see a SECURITY.md AND CONTRIBUTING.md still using the template 

**Describe the solution you'd like**
A clear and concise description of what i want to happen is a filled out security and contributing

**Describe alternatives you've considered**
leaving them there
Not caring and moving on
Neglecting budding timetable developers
Backdooring timwtabl.
Not timetabl 
**Additional context**
NEWS.md is also bad

**Comment by debater-coder** [comment]
fixed by commit https://github.com/debater-coder/timetabl-app/commit/208961366818bbdb045edcddc6a5b16085ac1204.
